apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: apache-qaz3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apache-qaz3
    app.kubernetes.io/part-of: devfile-sample-go-basic
  name: apache-qaz3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: apache-qaz3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: apache-qaz3
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/sde-rcook-tenant/devfile-sample-go-basic/apache-qaz3@sha256:12f10f654e8585183903904d45bab3254670b1e6073aa7c98f5ac911fed28479
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
