apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: apache-qaz3
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/sde-rcook-tenant/devfile-sample-go-basic/apache-qaz3@sha256:fd1f3d24fea921bbcf4bdcbd130b90af1a4b0420dfd451a940761aa4e302ce26
        name: container-image
        resources: {}
status: {}
